tic;
clear all; clc;
%Marsagalia's polar method
M1 = 1; % Mean of X
M2 = 2; % Mean of Y
V1 = 4; % Variance of X
V2 = 9; % Variance of Y
i = 0; % the random number generated by the algorithm 
count1 = 10000000;
count2 = 1000000;
% Geberate X and Y that are N(0,1) random variables and independent
while(i <= count1)
    u1 = 2*rand()-1;
    u2 = 2*rand()-1;
    s = u1^2 + u2^2;
    if(s < 1)
        i = i + 1;
        X(i) = sqrt(-2*log(s)/s)*u1;
        Y(i) = sqrt(-2*log(s)/s)*u2;
        if(i>=count2)
            break;
        end
    end
end

% Scale them to a particular mean and variance 
x = sqrt(V1)*X + M1; % x~ N(M1,V1)
y = sqrt(V2)*Y + M2; % y~ N(M2,V2)
toc;

A = x + y;
C = cov(x,y);
sample_mean = mean(A);
sample_var = std(A).^2;